JJ hcmi branch
PNNL-CompBio/candleDataProcessing pull request #30
Opened 2023-09-06 16:53 UTC by jjacobson95

Updates:

HCMI Data updated. Sample.tsv updated with improve IDs and cancer type data.

[figshare_pull.py](https://github.com/PNNL-CompBio/candleDataProcessing/compare/JJ_hcmi_branch?expand=1#diff-71bc69f5ab651e6fba551b5db8e47ad90e5bc9d0016c2b0496204cc8badce98a) script added.

[assign_improve_ids.py](https://github.com/PNNL-CompBio/candleDataProcessing/compare/JJ_hcmi_branch?expand=1#diff-37846375a779a3a8e848733ad31b4949350004391808a3e43cc30ef578ff1a90) script added.

2023-09-06 16:54 UTC, jjacobson95 commented
PR is ready. I will remove the CI soon though. This CI did not work due to Github memory constraints.

2023-09-06 17:36 UTC, sgosline requested changes
the sample file still isn't right - check the schema and update it before i merge.

2023-09-06 17:36 UTC, sgosline commented on hcmi/sample.tsv
this file is not to schema - we dont need all the HCMI data, but we need the columns to match. `improve_sample_id`, `cancer_type`, etc. all the others should be deleted, and the table should be a csv. cancer types should also be standardized. you can add all the additioinal identifiers in the `other_id` field

2023-09-06 18:09 UTC, jjacobson95 commented on hcmi/sample.tsv
Sorry about this - will do. Is there a list of cancer types that I should map to for renaming/standardizing?

2023-09-06 19:01 UTC, jjacobson95 commented
Added samples.csv to hcmi. Also added to figshare.

2023-09-07 00:39 UTC, sgosline commented on hcmi/sample.tsv
This is better. remove the indexing row, and i will merge. the cancer types require manual annotation, i usually use a dictionary. i'll take a look after it's merged.

2023-09-07 01:03 UTC, jjacobson95 commented on hcmi/sample.tsv
Updated!  Okay sounds good. Seems like Brian may already have an automated method for annotating cancer types across different datasets. But I'd be happy to update mine if there is a standard naming convention available.

2023-09-07 14:37 UTC, sgosline approved these changes

2023-09-07 14:38 UTC, merged